name: markai_mobile
description: A new Flutter project for MarkAi Platform.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Architecture & State
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  
  # Navigation
  go_router: ^13.0.0
  
  # Networking & Auth
  supabase_flutter: ^2.3.0
  
  # UI/UX
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.0.0
  
  # Utils
  easy_localization: ^3.0.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
